os: linux
sudo: required
language: generic

install:
  - sudo apt-get update -qq
  - gcc --version

before_script:
  - wget https://github.com/stateos/DemOS/archive/master.zip
  - unzip -q master.zip
  - mv DemOS-master/DemOS/* DemOS/
  - rm -r DemOS-master

script: make all
