os: linux
sudo: required
language: generic

install:
  - sudo apt-get update -qq
  - gcc --version

before_script:
  - wget https://github.com/stateos/DemOS/archive/master.zip
  - unzip -q master.zip
  - mv -T DemOS-master/DemOS/kernel/ DemOS/kernel/
  - mv -T DemOS-master/DemOS/port/ DemOS/port/
  - rm -r DemOS-master

script: make all
